// angular/sell-tickets/src/app/components/movie-item/movie-item.component.ts
import { Component, OnInit, Input} from '@angular/core';
import {Router} from '@angular/router'
@Component({
  selector: 'app-movie-item',
  templateUrl: './movie-item.component.html',
  styleUrls: ['./movie-item.component.scss']
})
export class MovieItemComponent implements OnInit {
    @Input() subjects:any;
  constructor(public router:Router) { }

  ngOnInit() {
  }
  handleDetail(id:number){
    this.router.navigate([`/film/${id}`])
  }
}

<div class="container" *ngFor="let data of subjects" (click)="handleDetail(data.id)">
    <slot name="icon"></slot>
    <div class="pic"><img [src]="data.images.small" alt=""></div>
     <div class="info">
         <p class="title">{{data.title}}</p>
         <span class="author">主演：<span *ngFor="let item of data.casts">{{item.name}} /</span></span>
         <p class="time">时长：{{data.durations[0]}}</p>
     </div>
</div>

// React/sell-tickets/src/components/MovieItem.js
import React, { Component } from 'react';
import Container from '../components-style/MovieItem-style'
class MovieItem extends Component {
    constructor(props){
        super(props);
    }
    render() {
        return (
            <Container> 
                {this.props.data.map((item,index)=>{
                    return (<div className="item" key={index} onClick={this.handleId.bind(this,item.id)}>
                        <div className="bg"><img src={item.images.small} alt=""/></div>
                        <div className="info">
                            <p className="title">{item.title}</p>
                            <p className="author">主演：{item.casts.map(item=>{
                                return (<span key={item.name}>{item.name} /</span>)
                            })}</p>
                            <p className="time">时长：{item.durations[0]}</p>
                        </div>
                    </div>)
                })}
            </Container>
        );
    }
    handleId=(id)=>{
        this.props.handleItem(id)
    }
}

export default MovieItem;
