// angular/wangyicat/src/app/components/music/music.component.ts
import { Component, OnInit } from '@angular/core';
import {HttpClient} from '@angular/common/http'
@Component({
  selector: 'app-music',
  templateUrl: './music.component.html',
  styleUrls: ['./music.component.scss']
})
export class MusicComponent implements OnInit {
    public playlists:any;
  constructor(public http:HttpClient) { }

  ngOnInit() {
    var url='http://192.168.14.15:5000/top/playlist?cat=华语'
    this.http.get(url).subscribe(res=>{
      this.playlists=res['playlists']
    })
  }

}

<div class="container">
    <div *ngFor="let item of playlists" class="item">
        <img [src]="item.coverImgUrl" alt="">
        <p>{{item.name}}</p>
    </div>
</div>

// React/musicmovie/src/Music/Music.js
import React, { Component } from 'react';
import './Music.css';
class Movie extends Component {
    constructor(props){
        super(props);
        this.state={
            playlists:[]
        }
    }
    render() {
        return (
            <div className="item">
               {this.state.playlists.map((item,index)=>{
                   return(<div key={index} onClick={this.handleDetail.bind(this,item.id)}>
                       <img src={item.coverImgUrl} alt={item.name}></img>
                        <p className="title">{item.name}</p>
                   </div>)
               })}
            </div>     
        );
    }
    componentDidMount() {
        var url='https://music.aityp.com/top/playlist?cat=韩语'
        this.axios.get(url).then(res=>{
           this.setState({
               playlists:res.data.playlists
           })
        })
    }
    handleDetail=(id)=>{
        this.props.history.push(`/MusicDetail?id=${id}`)
    }
    
}

export default Movie;
