// vue/element-todolist/src/App.vue
<template>
  <div id="app">
    <div class="nav">
         <div class="nav-title center">
          <span>ToDoList</span>
          <el-input v-model="keyword" placeholder="添加ToDo" clearable @keyup.enter.native="handleWord(keyword)"></el-input>
        </div>
    </div>
    <div class="to-container">
      <div class="content center">
        <div class="title">
          <p>正在进行</p>
        <span class="num">{{arr.length-sum}}</span>
        </div>
        <div class="list-f" v-for="item of arr" :key="item.index" v-show="!item.checked">
          <el-checkbox v-model="item.checked"></el-checkbox>
          <span>{{item.name}}</span>
          <span class="circle" @click="handleDelete(item)"><span class="min-circle">-</span></span>
        </div>

        <div class="title">
          <p>已经完成</p>
          <span class="num">{{sum}}</span>
        </div>     
        <div class="list-s" v-for="item of arr" :key="item.index" v-show="item.checked">
          <el-checkbox v-model="item.checked"></el-checkbox>
          <span>{{item.name}}</span>
          <span class="circle"  @click="handleDelete(item)"><span class="min-circle">-</span></span>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'app',
  data(){
    return{
      keyword:'',
      checked:false,
      arr:[],
    }
  },
  computed:{
    sum(){
      var sum =this.arr.filter(item=>item.checked);
      return sum.length
    }
  },
  methods:{
    handleWord(keyword){
      if(this.keyword !=""){
        var arr=this.arr;
        var obj={};
        obj.checked=this.checked;
        obj.name=this.keyword;
        arr.push(obj);
        this.keyword=""
      }
      
    },
    handleDelete(item){
        var arr=this.arr.filter(value=>value!==item)
        this.arr=arr
    }
  },
  updated(){
    localStorage.setItem("arr",JSON.stringify(this.arr))
  },
  mounted(){
    var arr=localStorage.getItem("arr");
    if(arr){
      this.arr=JSON.parse(arr)
    }else{
      localStorage.setItem("arr","[]")
    }
  }
}
</script>

<style scoped>
      .nav{
        height: 50px;
        width: 100%;
        background: #323232;
        color: white;
      }
      .nav-title{
        width: 500px;
        line-height:50px;
        display: flex;
        text-align: center
      }
      .center{
        margin: 0 auto;
      }
      .nav-title span{
        margin-right: 100px;
      }
      .el-input input{
        width: 400px;height: 200px;
      }
      .to-container{
        background: #CDCDCD;
        height: 575px;
      }
      .content{
        width: 500px;
      }
      #app{
        margin: 0;
        position: absolute;
        top: 0;left:0;
        width: 100%;
        min-height: 100%;
      }
      .title>p{
        font-size: 20px;
        font-weight: bold;
        padding-top: 20px;
        margin: 0;
      }
      .title{
        position: relative;
      }
      .num{
        width: 20px;height: 20px;
        display: inline-block;
        border-radius: 50%;
        text-align: center;
        background: #E6E6FA;
        position: absolute;
        top: 25px;right: 10px

      }
      .list-f,.list-s{
        line-height: 30px;
        background: white;
        border-radius: 5px;
        margin-top: 20px;
        position: relative;
      }
      .content .list-f{       
        border-left: 4px solid #629A9C;       
      }
      .content .list-s{     
        border-left: 4px solid #B3B3B3;
        opacity: .5;
      }
      .el-checkbox{
        margin: 0 15px;
      }
      .list span{
        margin-left: 15px;
      }
      .circle{
        width: 20px;height: 20px;
        border: 1px solid#333;      
        right: 10px;
      }
      .min-circle{
        width: 15px;height: 15px;
        background: #CDCDCD;
        right: 2px;
        color: white;
        text-align: center;
        line-height: 10px;
      }
      .circle,.min-circle{
        display: inline-block;
        border-radius: 50%;
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
      }
</style>

// React/todolist/src/App.js
import React, { Component } from 'react';
import './App.css'
import {Input,Checkbox} from 'antd'
class App extends Component {
  constructor(props){
    super(props);
    this.state={
      keyword:"",
      arrList:[],
      checked:false,
      id:1
    }
  }
  render() {
    return (
      <div>
            <div className="nav">
                <div className="nav-title center">
                  <span>ToDoList</span>
                  <Input type="text" placeholder="添加ToDo" size="small" value={this.state.keyword}
                  onPressEnter={this.addKey.bind(this,this.state.keyword)} onChange={this.addChange} />
                </div>
            </div>
            <div className="to-container">
              <div className="content center">
                <div className="title">
                  <p>正在进行</p>
                      <span className="num">{this.state.arrList.length-this.sum()}</span>
                </div>
                <div className="list-f">
                  {this.state.arrList.map((item,index)=>{
                    return (<div key={index} style={{display:(!item.checked)?"block":"none"}} className="item">
                      <Checkbox checked={item.checked}  onChange={this.handleFinish.bind(this,item.id)}></Checkbox>
                      <span>{item.name}</span>
                      <span className="circle" onClick={this.handleDelete.bind(this,item.id)}><span className="min-circle">-</span></span>
                    </div>)
                  })}
                    
                </div>
                <div className="title">
                  <p>已经完成</p>
                     <span className="num">{this.sum()}</span>
                </div>     
                <div className="list-s" >
                  {this.state.arrList.map((item,index)=>{
                    return (<div key={index} style={{display:(item.checked)?"block":"none"}} className="item">
                      <Checkbox checked={item.checked}  onChange={this.handleFinish.bind(this,item.id)}></Checkbox>
                      <span>{item.name}</span>
                      <span className="circle" onClick={this.handleDelete.bind(this,item.id)}><span className="min-circle">-</span></span>
                    </div>)
                  })}
                </div>
              </div>
            </div>
          </div>
      );
    }
    /* 改变keyword的值 */
    addChange=(e)=>{
      this.setState({
          keyword:e.target.value
      })
    }
    /* 回车键添加数组 */
    addKey=(e)=>{
      if(e!=""){
        var arrList=this.state.arrList;
        var keyword=e;
        var obj={};
        var id=this.state.id;
        obj.name=keyword;
        obj.checked=this.state.checked;
        obj.id=id
        id=id+1
        arrList.push(obj)
        this.setState({
          arrList,
          id
        })
      }
    }
    handleFinish=(id)=>{
        var arrList=this.state.arrList;
        /* 如果点击的id==当前id,则改变checked */
       arrList.forEach(item=>{
          if(item.id==id){
            item.checked=!item.checked
          }
        })
        this.setState({
          arrList
        })
    }
    handleDelete=(id)=>{
      var arrList=this.state.arrList;
      var index=arrList.findIndex(item=>{
        if(item.id==id){
          return true
        }
      })
      arrList.splice(index,1)
      this.setState({
        arrList
      })
    }
    sum(){
      /* item.checked默认为false,在未完成时的状态一直为false,长度一直为0,直到点击事件,checked为true，长度开始累加 */
      var sum=this.state.arrList.filter(item=>item.checked);
      return sum.length;
    }
    /* todoNumber() {
      var arrList = this.state.arrList
      var todolist = arrList.filter(item => {
        if (!item.checked) {
          return true
        }
      })
      return todolist.length
    } */
   /*  doneNumber() {
      var arrList = this.state.arrList
      var donelist = arrList.filter(item => {
        if (item.checked) {
          return true
        }
      })
      return donelist.length
    } */
}

export default App;
