// React/sell-tickets/src/ComingSoon/ComingSoon.js
import React, { Component } from 'react';
import axios from 'axios'
import MovieItem from '../components/MovieItem'
class ComingSoon extends Component {
    constructor(props){
        super(props);
        this.state={
            subjects:[]
        }
    }
    render() {
        return (
            <div>
                <MovieItem data={this.state.subjects} handleItem={this.handleFilms}></MovieItem>
            </div>
        );
    }
    componentDidMount() {
        var url='https://douban-api.now.sh/v2/movie/coming_soon'
        axios.get(url).then(res=>{
            this.setState({
                subjects:res.data.subjects
            })
        })
    }
    handleFilms=(id)=>{
        this.props.handleId(id)
    }
}
export default ComingSoon;

// angular/sell-tickets/src/app/components/coming-soon/coming-soon.component.ts
import { Component, OnInit } from '@angular/core';
import {HttpClient} from '@angular/common/http'
@Component({
  selector: 'app-coming-soon',
  templateUrl: './coming-soon.component.html',
  styleUrls: ['./coming-soon.component.scss']
})
export class ComingSoonComponent implements OnInit {
      public subjects:[];
  constructor(public http:HttpClient) { }

  ngOnInit() {
    var url='https://douban-api.now.sh/v2/movie/coming_soon';
    this.http.get(url).subscribe(res=>{
        this.subjects=res['subjects']
    })
  }

}
