// angular/sell-tickets/src/app/components/now-playing/now-playing.component.ts
import { Component, OnInit } from '@angular/core';
import {HttpClient} from '@angular/common/http'
@Component({
  selector: 'app-now-playing',
  templateUrl: './now-playing.component.html',
  styleUrls: ['./now-playing.component.scss']
})
export class NowPlayingComponent implements OnInit {
      public subjects:[];
  constructor(public http:HttpClient) { }

  ngOnInit() {
    var url="https://douban-api.now.sh/v2/movie/in_theaters";
    this.http.get(url).subscribe(res=>{
      this.subjects=res['subjects'];
    })
  }

}

<app-movie-item [subjects]="subjects"></app-movie-item>

// React/sell-tickets/src/NowPlaying/NowPlaying.js
import React, { Component } from 'react';
import axios from 'axios'
import MovieItem from '../components/MovieItem'
class NowPlaying extends Component {
    constructor(props){
        super(props);
        this.state={
            subjects:[],
        }
    }
    render() {
        return (
            <div>
                <MovieItem data={this.state.subjects} handleItem={this.handleFilms}></MovieItem>
            </div>
        );
    }
    componentDidMount(){
        var url='https://douban-api.now.sh/v2/movie/in_theaters'
        axios.get(url).then(res=>{
            this.setState({
                subjects:res.data.subjects
            })
        })
    }
    handleFilms=(id)=>{
        this.props.handleId(id)
    }
}

export default NowPlaying;
