// React/musicmovie/src/Music/Music.js
import React, { Component } from 'react';
import './Music.css';
class Movie extends Component {
    constructor(props){
        super(props);
        this.state={
            playlists:[]
        }
    }
    render() {
        return (
            <div className="item">
               {this.state.playlists.map((item,index)=>{
                   return(<div key={index} onClick={this.handleDetail.bind(this,item.id)}>
                       <img src={item.coverImgUrl} alt={item.name}></img>
                        <p className="title">{item.name}</p>
                   </div>)
               })}
            </div>     
        );
    }
    componentDidMount() {
        var url='https://music.aityp.com/top/playlist?cat=韩语'
        this.axios.get(url).then(res=>{
           this.setState({
               playlists:res.data.playlists
           })
        })
    }
    handleDetail=(id)=>{
        this.props.history.push(`/MusicDetail?id=${id}`)
    }
    
}

export default Movie;

// angular/music-movie/src/app/components/music/music.component.ts
import { Component, OnInit } from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {Router,NavigationExtras} from '@angular/router'
@Component({
  selector: 'app-music',
  templateUrl: './music.component.html',
  styleUrls: ['./music.component.scss']
})
export class MusicComponent implements OnInit {
    public playlists:any;
  constructor( public http:HttpClient,private router:Router) { }

  ngOnInit() {
    var url:string="http://192.168.14.15:5000/top/playlist?cat=华语";
    this.http.get(url).subscribe(res=>{
      this.playlists=res['playlists']
    })
  }
  handleDetail(id){
    console.log(id)
    let NavigationExtras:NavigationExtras={
      queryParams:{
        "id":id
      }
    }
    this.router.navigate(['/musicDetail'],NavigationExtras)
  }

}

<div class="container-flex">
    <div *ngFor="let item of playlists" class="item" (click)="handleDetail(item.id)">
        <img [src]="item.coverImgUrl" alt="">
        <p class="name">{{item.name}}</p>
    </div>
</div>
