// webpack/readbook/src/App.vue
<template>
    <div class="container">
        <div class="item" v-for="item of artists" :key="item.id">
            <img :src="item.picUrl" alt="" />
            <div class="name">{{item.name}}</div>
        </div>
    </div>
</template>
<script>
import axios from 'axios'
export default {  
    name:"App",
    data(){
        return{
            artists:[]
        }
    },
    mounted(){
        var url="https://music.aityp.com/top/artists";
        axios.get(url).then(res=>{
            this.artists=res.data.artists
            console.log(this.artists[0].name)
        })
    }
}
</script>

// React/delete/src/App.js
import React from 'react';
import Moive from './components/Movie'
class App extends React.Component{
  constructor(props){
    super(props)
    this.state={
      playlists:[]
    }
  }
  render(){
    return(
      <div>
        <Moive deleteItem={this.handleDelete.bind(this)} data={this.state.playlists}></Moive>
      </div>
    )
  }
  componentDidMount(){
    this.axios.get('https://music.aityp.com/top/playlist?cat=日语').then(res=>{
      this.setState({
        playlists:res.data.playlists
      })
    })
  }
  handleDelete(index){
    var playlists=this.state.playlists;
    playlists.splice(index,1)
    this.setState({
      playlists
    })
  }
}

export default App;
