// angular/sell-tickets/src/app/components/city/city.component.ts
import { Component, OnInit } from '@angular/core';
import {CommonService} from '../../services/common.service'
import {HttpClient} from '@angular/common/http'
import {Router} from '@angular/router'
@Component({
  selector: 'app-city',
  templateUrl: './city.component.html',
  styleUrls: ['./city.component.scss']
})
export class CityComponent implements OnInit {
    public cities:[];
    public hotCities:[];
  constructor(public http:HttpClient,public common:CommonService,public router:Router) { }

  ngOnInit() {
      var url='http://yapi.demo.qunar.com/mock/43104/film';
      this.http.get(url).subscribe(res=>{
        this.hotCities=res['data'].hotCities;
        this.cities=res['data'].cities;
      })
      
  }
  handleChangeCity(item:string){
    this.common.changeCity(item)
    this.router.navigate(['/films'])
  }
}

<div class="nav">
    <button>X</button>      
    <p>当前城市 - 武汉</p>
</div>
<div class="search">
    <i class="iconfont icon-sousuo"></i>
    <input
     type="text" placeholder="输入城市名或拼音">
    <button class="cancel">取消</button>
</div>
<div class="city">
    <div class="position">
        <p>GPS定位你所在城市</p>
        <span class="pos">武汉</span>
    </div>
    <div class="hot-city">
        <p>热门城市</p>
        <div>
            <span *ngFor="let item of hotCities" (click)="handleChangeCity(item.name)">{{item.name}}</span>
        </div>        
    </div>
    <!-- pipeName为管道修饰符  https://www.yuque.com/aying-iyhqu/zvw9ep/rxsnzk  -->
    <div *ngFor="let key of cities | pipeName">
        <div>{{key}}
            <div *ngFor="let item of cities[key]">
                <p (click)="handleChangeCity(item.name)">{{item.name}}</p>
            </div>
        </div>      
    </div>
 </div>

// React/sell-tickets/src/City/City.js
import React, { Component } from 'react';
import './City.css'
import {Input} from 'antd';
import axios from 'axios'
import store from '../store/index'
import '../Films/Films'
class City extends Component {
    constructor(props){
        super(props);
        this.state={
            hotCities:[],
            cities:"",
            newCity:store.getState()
        }
        store.subscribe(this.handleSotreChange)
    }
    render() {
        return (
            <div>
                <div>
                   {/*  <div className="nav">
                     <router-link to="/films/nowPlaying">
                    <button className="secede">X</button>
                </router-link>      */}     
                <p className="currentCity">当前城市 - 武汉</p>
            </div>
            <div className="search">
                <i className="iconfont icon-sousuo"></i>
                <input className="inp"
                 type="text" placeholder="输入城市名或拼音" />
               {/*  <button className="cancel" >取消</button> */}
            </div>
            <div className="content" id="search-content">
                <div className="city">
                    <div className="position">
                        <p>GPS定位你所在城市</p>
                        <span className="pos">武汉</span>
                    </div>
                    <div className="hot-city">
                        <p>热门城市</p>
                        <p>
                            {this.state.hotCities.map(item=>{
                                return (<span key={item.name} msg={this.state.city} onClick={this.handleCity.bind(this,item.name)}>{item.name}</span>)
                            })}
                        </p>
                    </div>
                </div>
                <div className="cities">
                    {Object.keys(this.state.cities).map((obj,value)=>{
                        return (<div key={value}>{obj} 
                                {this.state.cities[obj].map((item,index)=>{
                                    return (<p onClick={this.handleCity.bind(this,item.name)} key={index}>{item.name}</p>)
                                })}
                        </div>)
                    })}
                </div>
            </div>
            </div>
            
        );
    }
    componentDidMount() {
        var url='http://yapi.demo.qunar.com/mock/43104/film'
        axios.get(url).then(res=>{
            this.setState({
                hotCities:res.data.data.hotCities,
                cities:res.data.data.cities
            })
        })
    }
    handleCity=(city)=>{
        const action={
            type:"city_value",
            value:city
        }
        store.dispatch(action)
        this.props.history.push(`/films/nowPlaying`)
    }
    handleSotreChange=()=>{
        this.setState(store.getState())
    }
}

export default City;
