// angular/music-movie/src/app/components/movie/movie.component.ts
import { Component, OnInit } from '@angular/core';
import {HttpClient} from '@angular/common/http'
@Component({
  selector: 'app-movie',
  templateUrl: './movie.component.html',
  styleUrls: ['./movie.component.scss']
})
export class MovieComponent implements OnInit {
    public subjects:any;
  constructor(public http:HttpClient) { }

  ngOnInit() {
    var url:string='https://douban.uieee.com/v2/movie/top250';
    this.http.get(url).subscribe(res=>{
      this.subjects=res['subjects']
    })
  }

}

<div class="container-flex">
    <div [routerLink]="['/movieDetail',item.id]" *ngFor="let item of subjects" class="item">
        <img [src]="item.images.small" alt="">
        <p>{{item.title}}</p>
    </div>
</div>

// React/musicmovie/src/Movie/Movie.js
import React, { Component } from 'react';
import './Movie.css';
class Music extends Component {
    constructor(props){
        super(props);
        this.state={
            subjects:[],
            id:""
        }
    }
    render() {
        return (
            <div className="item">
               {this.state.subjects.map((item,index)=>{
                   return(<div key={index} onClick={this.handleMovie.bind(this,item.id)}>
                       <img src={item.images.small} alt={item.name}></img>
                        <p className="name">{item.title}</p>
                   </div>)
               })}
            </div>     
        );
    }
    componentDidMount() {
        var url='https://douban-api.zce.now.sh/v2/movie/top250'
        this.axios.get(url).then(res=>{
           this.setState({
            subjects:res.data.subjects
           })
        })
    }
    handleMovie=(id)=>{
        this.props.history.push(`/MovieDetail/${id}`)
    }
}

export default Music;
