// angular/music-movie/src/app/components/movie-detail/movie-detail.component.ts
import { Component, OnInit } from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {HttpClient} from '@angular/common/http'
@Component({
  selector: 'app-movie-detail',
  templateUrl: './movie-detail.component.html',
  styleUrls: ['./movie-detail.component.scss']
})
export class MovieDetailComponent implements OnInit {
    public data:any;
  constructor(public route:ActivatedRoute,public http:HttpClient) { }

  ngOnInit() {
    this.route.params.subscribe(res=>{
      var id=res.id
      var url=`https://douban-api.uieee.com/v2/movie/subject/${id}`
      this.http.get(url).subscribe(res=>{
        this.data=res
      })
    })
  }

}

<div class="container">
    <p>{{data.title}}<span>({{data.year}})</span></p>
    <img [src]="data.images.small" alt="">
    <div>
        <p>剧情介绍:</p>
        <p class="summary">{{data.summary}}</p>
    </div>
</div>

// React/musicmovie/src/MovieDetail/MovieDetail.js
import React, { Component } from 'react';
import './MovieDetail.css'
class MovieDetail extends Component {
    constructor(props){
        super(props);
        this.state={
            data:Object,
            pic:String
        }
    }
    render() {
        return (
            <div className="item">
                <p className="title">{this.state.data.title}<span>({this.state.data.year})</span></p>
                <img src={this.state.pic.small}></img>
                <p>{this.state.data.summary}</p>
            </div>
        );
    }
    componentDidMount() {
        var id=this.props.match.params.id
        this.axios.get(`https://douban-api.uieee.com/v2/movie/subject/${id}`).then(res=>{
             this.setState({
                data:res.data,
                pic:res.data.images
            })  
         }) 
    }
    
}

export default MovieDetail;
